# Generated by Django 5.2.1 on 2025-05-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitySearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, unique=True, verbose_name='Название города')),
                ('search_count', models.IntegerField(default=1, verbose_name='Количество запросов')),
            ],
            options={
                'verbose_name': 'История поиска городов',
                'verbose_name_plural': 'Истории поиска городов',
            },
        ),
    ]
