# Generated by Django 5.2.1 on 2025-05-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citysearchhistory',
            name='search_count',
            field=models.IntegerField(default=0, verbose_name='Количество запросов'),
        ),
    ]
