# Generated by Django 5.2.1 on 2025-05-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_citysearchhistory_search_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='citysearchhistory',
            name='session_key',
            field=models.CharField(db_index=True, default='default_session', max_length=32, verbose_name='Ключ сессии'),
            preserve_default=False,
        ),
    ]
