# Generated by Django 5.2.1 on 2025-05-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_citysearchhistory_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citysearchhistory',
            name='city_name',
            field=models.CharField(max_length=100, verbose_name='Название города'),
        ),
    ]
